#!/bin/bash

filename=$1
N=$2

./scripts/clean_output
./crowdsim "$filename" $N
echo "converting to mp4"
ffmpeg -r 3 -f image2  -i ./ppms/step-%03d.ppm -vcodec libx264 -crf 25  -pix_fmt yuv420p ./outputs/output.mp4


